baseURL = "https://tokyovoicelessons.com"
staticDir = ['static',]
languageCode = "en"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = "Tokyo Voice Lesson"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
disableKinds = ['sitemap']
# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Languages]
  [Languages.en]
  title = "Tokyo Voice Lessons"
  weight = 1
  contentDir = "content"
  LanguageName = "English"

  [Languages.jp]
  title = "東京ボイスレッスン"
  weight = 2
  contentDir = "content/jp"
  LanguageName = "日本語"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[[Languages.en.menu.main]]
url    = "/en/"
identifier = "home"
name   = "Home"
weight = 100

[[Languages.en.menu.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/en/posts/"

[[Languages.en.menu.main]]
name = "About"
weight = 300
identifier = "about"
url = "/en/about/"


[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

