title = "I'm Template TITLE"
author = "Reina"
copyright = "©{{ YEAR }} J-POP karaoke"
description = "Call me Template"
profilePicture = "images/profile1.jpeg"
keywords = ""
favicon = "favicons/"
customCss = ["css/custom.css", "css/bootstrap.min.css"]
customJs = ["js/custom.js"] 
mainSections = ["posts"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
displayMode = "light"
disableThemeSwitcher = true
contentratio = 0.8
fullPostContent = true
reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/lxndrblz/anatole/"

[[socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fab fa-kickstarter"
title = "kickstarter"
url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fab fa-patreon"
title = "patreon"
url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fab fa-reddit"
title = "reddit"
url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fab fa-snapchat"
title = "snapchat"
url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fab fa-twitch"
title = "snapchat"
url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fab fa-youtube"
title = "youtube"
url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fab fa-weixin"
title = "wechat"
url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fab fa-line"
title = "line"
url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fab fa-paypal"
title = "paypal"
url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fas fa-hand-holding-usd"
title = "onlyfan"
url = "todo only"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@example.com"
